title: दुतावास | Dutawas
description: Online repository to document services provided by Embassay of Nepal in US.
author: kshitu92
theme: just-the-docs

url: https://dutawas.com

aux_links:
  Github: https://github.com/kshitu92/dutawas

mermaid:
  version: ">=11.4.1"

incremental: true

callouts:
  warning:
    title: Warning
    color: red
  disclaimer:
    title: Disclaimer
    color: red
  info:
    title: Info
    color: blue

footer_content: |
  <p>Created and maintained by <a href="https://github.com/kshitu92/" target="_blank">Kshitu92</a> cuz यो मन त मेरो नेपाली हो |</p>
