title: दुतावास | Dutawas
description: Online repository to document services provided by Embassay of Nepal in US.
author: kshitu92
theme: just-the-docs

url: https://dutawas.com

aux_links:
  Template Repository: https://github.com/kshitu92/dutawas

mermaid:
  version: ">=11.4.1"

incremental: true
